### ISSUE TITLE
清洗后的数据集可否提供

### ISSUE THREAD

**Issue by 1148270327** [wptoux/albert-chinese-large-webqa#1]
感谢大佬的分享和研发，可否提供dureader和webQA处理过的数据集呢，便于我们用于训练，感谢

**Comment by wptoux** [comment]
我也不太清楚lincense的问题，是否允许发布百度的数据集。可以网上搜一下数据集，然后用我的webQA.ipynb，dureader.ipynb，merge.ipynb进行处理。
