### ISSUE TITLE
您好，您部署在hugging face 上的模型好像不能得到结果。

### ISSUE THREAD

**Issue by svjack** [wptoux/albert-chinese-large-webqa#3]
如题，https://huggingface.co/wptoux/albert-chinese-large-qa
上我看例子得不到结果。

**Comment by svjack** [comment]
我执行下面的代码
inputs = tokenizer.encode_plus(query, doc, return_tensors="pt")
start_scores, end_scores = model(**inputs)
start_scores 的输出是str而不是tensor

**Comment by svjack** [comment]
将版本进行降级后可以使用，最好更新一下模型版本，或者让官方部署api的版本降级。

**Comment by wptoux** [comment]
好的
